server:
  port: 8080

Spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: job-service
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/job/**
          filters:
            - JwtFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

#zuul:
#  routes:
#    AUTH-SERVICE:
#      path: /auth/**
#      serviceId: AUTH-SERVICE
#    JOB-SERVICE:
#      path: /job/**
#      serviceId: JOB-SERVICE

